baseURL = "http://example.com/"
languageCode = "en-us"
title = "Bird's Eye Reproducibility"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Ciera Martinez"
    description = "Wyoming INBRE 2020 Summer of Code"
    githubUsername = "#"
    accent = "purple"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "Schedule"
    weight = 2

# [[menu.main]]
#    url = "/post/"
#   name = "Content"
#   weight = 3

#[[menu.main]]
#    url = "/resources/"
#    name = "Resources"
#    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "ccmartinez@berkeley.edu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/iamciera/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/cierareports"
    name = "twitter"
    weight = 3



